# Generated by Django 2.2.2 on 2019-06-23 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_auto_20190623_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 47, 37, 623559)),
        ),
    ]
